/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'plumber' : IDL.Null,
  'electrician' : IDL.Null,
  'mechanic' : IDL.Null,
  'deepCleaning' : IDL.Null,
  'pestControl' : IDL.Null,
  'acService' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceCategory' : ServiceCategory,
  'customerLocation' : IDL.Text,
  'customerPhone' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'createdAt' : IDL.Int,
  'customerId' : IDL.Principal,
  'amount' : IDL.Nat,
  'providerId' : IDL.Principal,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ProviderProfile = IDL.Record({
  'serviceCategory' : ServiceCategory,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'totalEarnings' : IDL.Nat,
  'totalReviews' : IDL.Nat,
  'idProofBlobId' : IDL.Opt(IDL.Text),
  'avgRating' : IDL.Float64,
});
export const RevenueStats = IDL.Record({
  'category' : ServiceCategory,
  'totalRevenue' : IDL.Nat,
  'bookingCount' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'provider' : IDL.Null,
  'customer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'passwordHash' : IDL.Vec(IDL.Nat8),
});
export const Review = IDL.Record({
  'bookingId' : IDL.Text,
  'createdAt' : IDL.Int,
  'comment' : IDL.Text,
  'customerId' : IDL.Principal,
  'rating' : IDL.Nat,
  'providerId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveProvider' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'adminGetAllBookings' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'adminGetAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
  'adminGetPendingProviders' : IDL.Func(
      [],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'adminGetRevenueStats' : IDL.Func([], [IDL.Vec(RevenueStats)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Principal,
        ServiceCategory,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'getAllApprovedProviders' : IDL.Func(
      [],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'getApprovedProviders' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyBookingsAsCustomer' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyBookingsAsProvider' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyProfile' : IDL.Func([], [User], ['query']),
  'getMyProviderProfile' : IDL.Func([], [ProviderProfile], ['query']),
  'getReviewsForProvider' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8)],
      [UserRole, IDL.Text],
      [],
    ),
  'markBookingCompleted' : IDL.Func([IDL.Text], [], []),
  'markBookingPaid' : IDL.Func([IDL.Text], [], []),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
      [],
      [],
    ),
  'registerProvider' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, ServiceCategory],
      [],
      [],
    ),
  'respondToBooking' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
  'uploadIdProof' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'plumber' : IDL.Null,
    'electrician' : IDL.Null,
    'mechanic' : IDL.Null,
    'deepCleaning' : IDL.Null,
    'pestControl' : IDL.Null,
    'acService' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceCategory' : ServiceCategory,
    'customerLocation' : IDL.Text,
    'customerPhone' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'createdAt' : IDL.Int,
    'customerId' : IDL.Principal,
    'amount' : IDL.Nat,
    'providerId' : IDL.Principal,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ProviderProfile = IDL.Record({
    'serviceCategory' : ServiceCategory,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'totalEarnings' : IDL.Nat,
    'totalReviews' : IDL.Nat,
    'idProofBlobId' : IDL.Opt(IDL.Text),
    'avgRating' : IDL.Float64,
  });
  const RevenueStats = IDL.Record({
    'category' : ServiceCategory,
    'totalRevenue' : IDL.Nat,
    'bookingCount' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'provider' : IDL.Null,
    'customer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'passwordHash' : IDL.Vec(IDL.Nat8),
  });
  const Review = IDL.Record({
    'bookingId' : IDL.Text,
    'createdAt' : IDL.Int,
    'comment' : IDL.Text,
    'customerId' : IDL.Principal,
    'rating' : IDL.Nat,
    'providerId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveProvider' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'adminGetAllBookings' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'adminGetAllProviders' : IDL.Func(
        [],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'adminGetPendingProviders' : IDL.Func(
        [],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'adminGetRevenueStats' : IDL.Func([], [IDL.Vec(RevenueStats)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Principal,
          ServiceCategory,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'getAllApprovedProviders' : IDL.Func(
        [],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'getApprovedProviders' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyBookingsAsCustomer' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyBookingsAsProvider' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyProfile' : IDL.Func([], [User], ['query']),
    'getMyProviderProfile' : IDL.Func([], [ProviderProfile], ['query']),
    'getReviewsForProvider' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [UserRole, IDL.Text],
        [],
      ),
    'markBookingCompleted' : IDL.Func([IDL.Text], [], []),
    'markBookingPaid' : IDL.Func([IDL.Text], [], []),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
        [],
        [],
      ),
    'registerProvider' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, ServiceCategory],
        [],
        [],
      ),
    'respondToBooking' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'uploadIdProof' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };