/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Booking {
  'id' : string,
  'customerName' : string,
  'status' : BookingStatus,
  'serviceCategory' : ServiceCategory,
  'customerLocation' : string,
  'customerPhone' : string,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'createdAt' : bigint,
  'customerId' : Principal,
  'amount' : bigint,
  'providerId' : Principal,
}
export type BookingStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface ProviderProfile {
  'serviceCategory' : ServiceCategory,
  'userId' : Principal,
  'name' : string,
  'email' : string,
  'approvalStatus' : ApprovalStatus,
  'totalEarnings' : bigint,
  'totalReviews' : bigint,
  'idProofBlobId' : [] | [string],
  'avgRating' : number,
}
export interface RevenueStats {
  'category' : ServiceCategory,
  'totalRevenue' : bigint,
  'bookingCount' : bigint,
}
export interface Review {
  'bookingId' : string,
  'createdAt' : bigint,
  'comment' : string,
  'customerId' : Principal,
  'rating' : bigint,
  'providerId' : Principal,
}
export type ServiceCategory = { 'plumber' : null } |
  { 'electrician' : null } |
  { 'mechanic' : null } |
  { 'deepCleaning' : null } |
  { 'pestControl' : null } |
  { 'acService' : null };
export interface User {
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'passwordHash' : Uint8Array,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'provider' : null } |
  { 'customer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveProvider' : ActorMethod<[Principal, boolean], undefined>,
  'adminGetAllBookings' : ActorMethod<[[] | [string]], Array<Booking>>,
  'adminGetAllProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'adminGetPendingProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'adminGetRevenueStats' : ActorMethod<[], Array<RevenueStats>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createBooking' : ActorMethod<
    [Principal, ServiceCategory, string, string, string, string, string],
    string
  >,
  'getAllApprovedProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'getApprovedProviders' : ActorMethod<
    [ServiceCategory],
    Array<ProviderProfile>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyBookingsAsCustomer' : ActorMethod<[], Array<Booking>>,
  'getMyBookingsAsProvider' : ActorMethod<[], Array<Booking>>,
  'getMyProfile' : ActorMethod<[], User>,
  'getMyProviderProfile' : ActorMethod<[], ProviderProfile>,
  'getReviewsForProvider' : ActorMethod<[Principal], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginWithCredentials' : ActorMethod<
    [string, Uint8Array],
    [UserRole, string]
  >,
  'markBookingCompleted' : ActorMethod<[string], undefined>,
  'markBookingPaid' : ActorMethod<[string], undefined>,
  'registerCustomer' : ActorMethod<[string, Uint8Array, string], undefined>,
  'registerProvider' : ActorMethod<
    [string, Uint8Array, string, ServiceCategory],
    undefined
  >,
  'respondToBooking' : ActorMethod<[string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitReview' : ActorMethod<[string, bigint, string], string>,
  'uploadIdProof' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];